# Generated by Django 4.2.5 on 2023-12-22 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersession",
            old_name="id",
            new_name="session_id",
        ),
    ]
