# Generated by Django 4.2.5 on 2024-01-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_confirmationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="confirmationcode",
            name="expiration_date",
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
