# Generated by Django 4.2.5 on 2024-01-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_confirmationcode_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmationcode",
            name="expiration_date",
            field=models.DateTimeField(),
        ),
    ]
