# Generated by Django 4.2.5 on 2024-01-08 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_alter_confirmationcode_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmationcode",
            name="expiration_date",
            field=models.DateTimeField(),
        ),
    ]
