# Generated by Django 4.2.5 on 2024-01-08 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_remove_confirmationcode_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="confirmationcode",
            name="expiration_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
