# Generated by Django 4.2.5 on 2024-01-09 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_remove_confirmationcode_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="confirmationcode",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 9, 5, 50, 32, 952798, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
