# Generated by Django 4.2.5 on 2024-01-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_confirmationcode_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmationcode",
            name="expiration_date",
            field=models.DateTimeField(default="2024-01-09T00:00:00Z"),
        ),
    ]
