# Generated by Django 4.2.5 on 2024-01-14 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0020_alter_confirmationcode_expiration_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmationcode",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 14, 18, 8, 18, 959363, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
