# Generated by Django 4.2.5 on 2024-01-26 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0023_alter_confirmationcode_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmationcode",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 26, 6, 46, 57, 965932, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
